version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - gil0mendes
  labels:
  - dependencies
  ignore:
  - dependency-name: node-resque
    versions:
    - 8.2.1
    - 8.2.2
    - 8.2.3
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
  - dependency-name: ws
    versions:
    - 7.4.2
    - 7.4.3
    - 7.4.4
  - dependency-name: chalk
    versions:
    - 4.1.0
  - dependency-name: browser_fingerprint
    versions:
    - 2.0.2
