sudo: false

language: node_js

node_js:
  - "6"

env:
  - "FAKEREDIS=true"
  - "FAKEREDIS=false"

os:
  - linux
  # - osx

before_script:
  - npm install -g gulp
  - gulp babel

script: npm run-script test:travis

services:
  - redis-server
  - mongodb

after_script:
  - npm run-script coverage

after_failure:
  - "cat /home/travis/build/gil0mendes/stellar/npm-debug.log"
