sudo: false

language: node_js

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

node_js:
# - "7"
  - "8"

env:
  - "FAKEREDIS=true CXX=g++-4.8"
  - "FAKEREDIS=false CXX=g++-4.8"

os:
  - linux
  # - osx

before_script:
  - npm run build

script: npm run-script test:travis

services:
  - redis-server
  - mongodb

after_script:
  - npm run-script coverage

after_failure:
  - "cat /home/travis/build/StellarFw/stellar/npm-debug.log"
